name: Deployment Pipeline

on: 
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: oneki
          heroku_email: ${{ secrets.HEROKU_EMAIL }}
          branch: main
          healthcheck: https://oneki.herokuapp.com/healt