name: Deployment Pipeline

on: 
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - run: ls
      - uses: devtomio/action-railway@v1.1.4
      #   with:
      #     railway_token: ${{ secrets.RAILWAY_TOKEN }}